<a href="https://colab.research.google.com/github/mohdfaazkhan/Machine-Learning/blob/main/4_save_and_load_model_using_pickle_and_joblib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Machine Learning With Python: Save And Load Trained Model**

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
from google.colab import files
uploaded = files.upload()

Saving homeprice.txt to homeprice.txt


In [5]:
df = pd.read_csv("homeprice.txt")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [7]:
model.coef_

array([135.78767123])

In [8]:
model.intercept_

180616.43835616432

In [9]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

**Save Model To a File Using Python Pickle**

In [10]:
import pickle

In [11]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

**Load Saved Model**

In [12]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [13]:
mp.coef_

array([135.78767123])

In [14]:
mp.intercept_

180616.43835616432

In [15]:
mp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

**Save Trained Model Using joblib**

In [19]:
import joblib

In [20]:
joblib.dump(model, 'model_joblib')

['model_joblib']

**Load Saved Model**

In [21]:
mj = joblib.load('model_joblib')

In [22]:
mj.coef_

array([135.78767123])

In [23]:
mj.intercept_

180616.43835616432

In [24]:
mj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])